### PR TITLE
Adding chromebook video.

### PR DESCRIPTION
**Pull request by Anish-Agnihotri**
Was adding in the Android instructions earlier today and noticed we didn't have a video guide for Chromebook instructions. 

So, I quickly whipped up a VM, installed Chrome OS, and recorded a video of the process: https://www.youtube.com/watch?v=JNzDIMoaMSc

Feel free to let me know if I should edit the video to include the user accessing their portal at the end (similar to the Windows videos). 

Also, might be a good idea to re-upload all the other videos to the official DAppNode YouTube account, and change their source of origin in `VideoInstructions.js`, so that everything is cohesive.

Thanks,

Anish

### CODE REVIEW

**Review by dapplion — DISMISSED** [review]
Looks good to me!

**Comment by Anish-Agnihotri** [comment]
Great! Made another commit to quickly fix the merge error between the last PR and this one (since approving the Android one caused their to be a one-line merge conflict in this one).

**Comment by Shelpin** [comment]
Hey @Anish-Agnihotri !!! thanks a lot for your contribution!! awesome!!!! we really appreciate it... as you were mentioning if it is not too much asking, it would be great if the video could finish with the connection already established, or even better as you mentioned, connected to the  DappNode admin UI.... that would be really great!! Thanks a lot!!

**Comment by Anish-Agnihotri** [comment]
Sounds good, I'll rerecord and add in the part where it connects to the admin UI.

**Comment by Anish-Agnihotri** [comment]
Turns out it's a bit more difficult than I expected to emulate networking properly under a VM, and I can't figure out the networking setup I had used previously, haha.

I'll try again tomorrow with a bootable Chrome OS usb and see if the native hardware support does any better.

**Comment by dapplion** [comment]
Thank you so much @Anish-Agnihotri but since we are moving to OpenVPN there's no need for the video.

**Pull request closed without merging**
